export interface QualNode {
  level: number;
  name: string;
  label: string;
  branches: { value: string; label: string }[];
}

export const QUAL_TREE: QualNode[] = [
  { level: 1, name: "10th", label: "10th / Matriculation", branches: [] },
  {
    level: 2, name: "12th", label: "12th / Intermediate / HSC", branches: [
      { value: "Science (PCM)", label: "Science – PCM (Physics, Chemistry, Maths)" },
      { value: "Science (PCB)", label: "Science – PCB (Physics, Chemistry, Biology)" },
      { value: "Commerce", label: "Commerce" },
      { value: "Arts", label: "Arts / Humanities" },
      { value: "Vocational", label: "Vocational" },
    ]
  },
  {
    level: 3, name: "ITI", label: "ITI Certificate", branches: [
      { value: "Electrician", label: "Electrician" },
      { value: "Fitter", label: "Fitter" },
      { value: "Welder", label: "Welder" },
      { value: "Turner", label: "Turner" },
      { value: "Machinist", label: "Machinist" },
      { value: "Plumber", label: "Plumber" },
      { value: "Carpenter", label: "Carpenter" },
      { value: "Painter", label: "Painter" },
      { value: "Mason", label: "Mason" },
      { value: "Motor Mechanic", label: "Motor Mechanic" },
      { value: "Diesel Mechanic", label: "Diesel Mechanic" },
      { value: "Refrigeration and AC Mechanic", label: "Refrigeration & AC Mechanic" },
      { value: "Electronics Mechanic", label: "Electronics Mechanic" },
      { value: "Instrument Mechanic", label: "Instrument Mechanic" },
      { value: "COPA", label: "COPA (Computer Operator)" },
      { value: "Draughtsman Civil", label: "Draughtsman Civil" },
      { value: "Draughtsman Mechanical", label: "Draughtsman Mechanical" },
      { value: "Sheet Metal Worker", label: "Sheet Metal Worker" },
      { value: "Wireman", label: "Wireman" },
      { value: "Stenographer", label: "Stenographer" },
      { value: "Surveyor", label: "Surveyor" },
      { value: "Solar Technician", label: "Solar Technician" },
      { value: "Network Technician", label: "Network Technician" },
      { value: "Foundry Man", label: "Foundry Man" },
      { value: "Blacksmith", label: "Blacksmith" },
      { value: "Electroplater", label: "Electroplater" },
      { value: "Rubber Technician", label: "Rubber Technician" },
      { value: "Book Binder", label: "Book Binder" },
      { value: "Photographer", label: "Photographer" },
    ]
  },
  {
    level: 3, name: "Diploma", label: "Diploma / Polytechnic", branches: [
      { value: "CSE", label: "Computer Science & Engineering (CSE)" },
      { value: "IT", label: "Information Technology (IT)" },
      { value: "Mechanical", label: "Mechanical Engineering" },
      { value: "Civil", label: "Civil Engineering" },
      { value: "Electrical", label: "Electrical Engineering" },
      { value: "EEE", label: "Electrical & Electronics (EEE)" },
      { value: "ECE", label: "Electronics & Communication (ECE)" },
      { value: "Chemical", label: "Chemical Engineering" },
      { value: "Automobile", label: "Automobile Engineering" },
      { value: "Production", label: "Production Engineering" },
      { value: "Instrumentation", label: "Instrumentation Engineering" },
      { value: "Mining", label: "Mining Engineering" },
      { value: "Textile", label: "Textile Engineering" },
      { value: "Architecture", label: "Architecture" },
      { value: "Pharmacy", label: "Pharmacy (D.Pharm)" },
      { value: "Medical Lab Technology", label: "Medical Lab Technology (DMLT)" },
      { value: "Hotel Management", label: "Hotel Management" },
      { value: "Fashion Design", label: "Fashion Design" },
    ]
  },
  { level: 3, name: "GNM", label: "GNM (General Nursing & Midwifery)", branches: [] },
  { level: 3, name: "ANM", label: "ANM (Auxiliary Nurse Midwife)", branches: [] },
  { level: 3, name: "D.Pharm", label: "D.Pharm (Diploma in Pharmacy)", branches: [] },
  {
    level: 4, name: "B.Tech", label: "B.Tech / BE (Engineering)", branches: [
      { value: "CSE", label: "CSE" },
      { value: "IT", label: "IT" },
      { value: "Mechanical", label: "Mechanical" },
      { value: "Civil", label: "Civil" },
      { value: "Electrical", label: "Electrical" },
      { value: "EEE", label: "EEE" },
      { value: "ECE", label: "ECE" },
      { value: "Chemical", label: "Chemical" },
      { value: "Aerospace", label: "Aerospace" },
      { value: "Automobile", label: "Automobile" },
      { value: "Production", label: "Production" },
      { value: "Industrial", label: "Industrial" },
      { value: "Instrumentation", label: "Instrumentation" },
      { value: "Mining", label: "Mining" },
      { value: "Metallurgy", label: "Metallurgy" },
      { value: "Biotechnology", label: "Biotechnology" },
      { value: "Environmental Engineering", label: "Environmental Engineering" },
      { value: "Marine", label: "Marine" },
      { value: "Textile", label: "Textile" },
      { value: "AI", label: "AI / Artificial Intelligence" },
      { value: "Data Science", label: "Data Science" },
      { value: "Cyber Security", label: "Cyber Security" },
      { value: "Software Engineering", label: "Software Engineering" },
      { value: "Network Engineering", label: "Network Engineering" },
      { value: "VLSI", label: "VLSI" },
      { value: "Embedded Systems", label: "Embedded Systems" },
      { value: "Robotics", label: "Robotics" },
      { value: "Petroleum", label: "Petroleum" },
      { value: "Nuclear", label: "Nuclear" },
      { value: "Agricultural Engineering", label: "Agricultural Engineering" },
      { value: "Biomedical", label: "Biomedical" },
      { value: "Food Technology", label: "Food Technology" },
      { value: "Nanotechnology", label: "Nanotechnology" },
    ]
  },
  {
    level: 4, name: "B.Sc", label: "B.Sc (Science)", branches: [
      { value: "Physics", label: "Physics" },
      { value: "Chemistry", label: "Chemistry" },
      { value: "Mathematics", label: "Mathematics" },
      { value: "Statistics", label: "Statistics" },
      { value: "Biology", label: "Biology" },
      { value: "Zoology", label: "Zoology" },
      { value: "Botany", label: "Botany" },
      { value: "Microbiology", label: "Microbiology" },
      { value: "Biochemistry", label: "Biochemistry" },
      { value: "Environmental Science", label: "Environmental Science" },
      { value: "Geology", label: "Geology" },
      { value: "Geography", label: "Geography" },
      { value: "Computer Science", label: "Computer Science (B.Sc CS)" },
      { value: "Electronics", label: "Electronics (B.Sc)" },
      { value: "Biotechnology", label: "Biotechnology" },
      { value: "Forensic Science", label: "Forensic Science" },
      { value: "Agriculture", label: "Agriculture" },
      { value: "Nursing", label: "Nursing (B.Sc Nursing)" },
    ]
  },
  {
    level: 4, name: "BA", label: "BA (Arts / Humanities)", branches: [
      { value: "Economics", label: "Economics" },
      { value: "History", label: "History" },
      { value: "Political Science", label: "Political Science" },
      { value: "Sociology", label: "Sociology" },
      { value: "Psychology", label: "Psychology" },
      { value: "Public Administration", label: "Public Administration" },
      { value: "Social Work", label: "Social Work" },
      { value: "English", label: "English" },
      { value: "Hindi", label: "Hindi" },
      { value: "Sanskrit", label: "Sanskrit" },
      { value: "Urdu", label: "Urdu" },
      { value: "Bengali", label: "Bengali" },
      { value: "Tamil", label: "Tamil" },
      { value: "Telugu", label: "Telugu" },
      { value: "Marathi", label: "Marathi" },
      { value: "Kannada", label: "Kannada" },
      { value: "Malayalam", label: "Malayalam" },
      { value: "Odia", label: "Odia" },
      { value: "Punjabi", label: "Punjabi" },
      { value: "Gujarati", label: "Gujarati" },
      { value: "Journalism", label: "Journalism / Mass Communication" },
      { value: "Philosophy", label: "Philosophy" },
      { value: "Anthropology", label: "Anthropology" },
      { value: "Geography", label: "Geography" },
      { value: "International Relations", label: "International Relations" },
      { value: "Defence Studies", label: "Defence Studies" },
      { value: "Fine Arts", label: "Fine Arts" },
      { value: "Music", label: "Music" },
      { value: "Physical Education", label: "Physical Education" },
      { value: "Library Science", label: "Library Science" },
      { value: "Education", label: "Education" },
    ]
  },
  {
    level: 4, name: "B.Com", label: "B.Com (Commerce)", branches: [
      { value: "Accounting", label: "Accounting" },
      { value: "Finance", label: "Finance" },
      { value: "Banking", label: "Banking & Insurance" },
      { value: "Taxation", label: "Taxation" },
      { value: "Marketing", label: "Marketing" },
      { value: "Human Resource", label: "Human Resource" },
      { value: "International Business", label: "International Business" },
    ]
  },
  { level: 4, name: "BCA", label: "BCA (Computer Applications)", branches: [{ value: "Computer Applications", label: "Computer Applications" }] },
  {
    level: 4, name: "BBA", label: "BBA / BBM (Business Administration)", branches: [
      { value: "Business Administration", label: "Business Administration" },
      { value: "Marketing", label: "Marketing" },
      { value: "Finance", label: "Finance" },
      { value: "Human Resource", label: "Human Resource" },
      { value: "Operations", label: "Operations" },
      { value: "Hospital Management", label: "Hospital Management" },
      { value: "Aviation Management", label: "Aviation Management" },
      { value: "Hotel Management", label: "Hotel Management" },
    ]
  },
  { level: 4, name: "B.Pharm", label: "B.Pharm (Pharmacy)", branches: [{ value: "Pharmacy", label: "Pharmacy" }] },
  { level: 4, name: "MBBS", label: "MBBS (Medicine)", branches: [] },
  { level: 4, name: "BDS", label: "BDS (Dental Surgery)", branches: [] },
  { level: 4, name: "BAMS", label: "BAMS (Ayurvedic Medicine)", branches: [] },
  { level: 4, name: "BHMS", label: "BHMS (Homeopathic Medicine)", branches: [] },
  { level: 4, name: "BUMS", label: "BUMS (Unani Medicine)", branches: [] },
  { level: 4, name: "B.Sc Nursing", label: "B.Sc Nursing", branches: [{ value: "Nursing", label: "Nursing" }] },
  { level: 4, name: "LLB", label: "LLB / BA LLB (Law)", branches: [{ value: "Law", label: "Law" }] },
  { level: 4, name: "B.Ed", label: "B.Ed (Education)", branches: [{ value: "Education", label: "Education" }] },
  { level: 4, name: "B.Arch", label: "B.Arch (Architecture)", branches: [{ value: "Architecture", label: "Architecture" }] },
  { level: 4, name: "CA", label: "CA (Chartered Accountant)", branches: [{ value: "CA", label: "Chartered Accountancy" }] },
  { level: 4, name: "CS", label: "CS (Company Secretary)", branches: [{ value: "CS", label: "Company Secretaryship" }] },
  { level: 4, name: "CMA", label: "CMA / ICWA (Cost Accountant)", branches: [{ value: "CMA", label: "Cost Management Accountancy" }] },
  {
    level: 5, name: "M.Tech", label: "M.Tech / ME (Engineering PG)", branches: [
      { value: "CSE", label: "CSE" },
      { value: "IT", label: "IT" },
      { value: "Mechanical", label: "Mechanical" },
      { value: "Civil", label: "Civil" },
      { value: "Electrical", label: "Electrical" },
      { value: "ECE", label: "ECE" },
      { value: "Chemical", label: "Chemical" },
      { value: "Structural", label: "Structural Engineering" },
      { value: "AI", label: "AI / Machine Learning" },
      { value: "Data Science", label: "Data Science" },
      { value: "VLSI", label: "VLSI" },
      { value: "Embedded Systems", label: "Embedded Systems" },
    ]
  },
  {
    level: 5, name: "MBA", label: "MBA / PGDM (Management PG)", branches: [
      { value: "Business Administration", label: "General Management" },
      { value: "Finance", label: "Finance" },
      { value: "Marketing", label: "Marketing" },
      { value: "Human Resource", label: "Human Resource" },
      { value: "Operations", label: "Operations" },
      { value: "Information Technology", label: "IT Management" },
      { value: "Hospital Management", label: "Hospital Management" },
      { value: "International Business", label: "International Business" },
    ]
  },
  {
    level: 5, name: "M.Sc", label: "M.Sc (Science PG)", branches: [
      { value: "Physics", label: "Physics" },
      { value: "Chemistry", label: "Chemistry" },
      { value: "Mathematics", label: "Mathematics" },
      { value: "Statistics", label: "Statistics" },
      { value: "Biology", label: "Biology" },
      { value: "Microbiology", label: "Microbiology" },
      { value: "Biochemistry", label: "Biochemistry" },
      { value: "Biotechnology", label: "Biotechnology" },
      { value: "Computer Science", label: "Computer Science" },
      { value: "Environmental Science", label: "Environmental Science" },
      { value: "Forensic Science", label: "Forensic Science" },
      { value: "Geology", label: "Geology" },
      { value: "Geography", label: "Geography" },
    ]
  },
  {
    level: 5, name: "MA", label: "MA (Arts / Humanities PG)", branches: [
      { value: "Economics", label: "Economics" },
      { value: "History", label: "History" },
      { value: "Political Science", label: "Political Science" },
      { value: "Sociology", label: "Sociology" },
      { value: "Psychology", label: "Psychology" },
      { value: "Public Administration", label: "Public Administration" },
      { value: "English", label: "English" },
      { value: "Hindi", label: "Hindi" },
      { value: "Journalism", label: "Journalism / Mass Communication" },
      { value: "Social Work", label: "Social Work" },
    ]
  },
  {
    level: 5, name: "M.Com", label: "M.Com (Commerce PG)", branches: [
      { value: "Accounting", label: "Accounting" },
      { value: "Finance", label: "Finance" },
      { value: "Taxation", label: "Taxation" },
    ]
  },
  { level: 5, name: "MCA", label: "MCA (Computer Applications PG)", branches: [{ value: "Computer Applications", label: "Computer Applications" }] },
  { level: 5, name: "LLM", label: "LLM (Law PG)", branches: [{ value: "Law PG", label: "Law" }] },
  { level: 5, name: "M.Ed", label: "M.Ed (Education PG)", branches: [{ value: "Education", label: "Education" }] },
  { level: 5, name: "M.Pharm", label: "M.Pharm (Pharmacy PG)", branches: [{ value: "M.Pharm", label: "Pharmacy" }] },
  { level: 5, name: "M.Arch", label: "M.Arch (Architecture PG)", branches: [{ value: "Architecture", label: "Architecture" }] },
  { level: 6, name: "PhD", label: "PhD / Doctorate", branches: [] },
];

export const LEVEL_GROUPS = [
  { id: 1, label: "10th / Matriculation", levels: [1] },
  { id: 2, label: "12th / Intermediate", levels: [2] },
  { id: 3, label: "Diploma & ITI", levels: [3] },
  { id: 4, label: "Graduation (Bachelor's)", levels: [4] },
  { id: 5, label: "Post-Graduation (Master's)", levels: [5] },
  { id: 6, label: "PhD / Research", levels: [6] },
];
